#!/bin/sh

DAEMON="IrRelayDaemon"
SCRIPT="/etc/$DAEMON/start$DAEMON.sh"

start() {
        printf 'Starting %s: ' "$DAEMON"
        start-stop-daemon --start --background --startas "$SCRIPT"
        status=$?
        if [ "$status" -eq 0 ]; then
                echo "OK"
        else
                echo "FAIL"
        fi
        return "$status"
}

stop() {
        printf 'Stopping %s: ' "$DAEMON"
        start-stop-daemon --stop --exec "/bin/$DAEMON"
        status=$?
        if [ "$status" -eq 0 ]; then
                echo "OK"
        else
                echo "FAIL"
        fi
        return "$status"
}

restart() {
        stop
        start
}

case "$1" in
        start|stop|restart)
                "$1";;
        reload)
                restart;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac
